name = "1suite/solder"
version = "0.3.0"
description = "A bundler for Roblox models"
authors = ["AstonishedLiker"]
repository = "https://github.com/1suite/Solder"
license = "MIT"

includes = [
    "bin/**",
    "src/**",
    ".luaurc",
    "pesde.toml",
    "LICENSE.txt",
    "README.md"
]

[target]
environment = "lune"
build_files = ["src"]
lib = "src/init.luau"
bin = "bin/init.luau"

[engines]
pesde = "^0.7.0"
lune = "=0.10.1"

[indices]
default = "https://github.com/pesde-pkg/index"
